name: Apply EF Migrations

env:
  PATH: MailAPI.Infrastructure

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: cd ${{ env.PATH }} && dotnet restore
    - name: Build
      run: cd ${{ env.PATH }} && dotnet build --no-restore
    - name: Apply Migrations
      run: cd ${{ env.PATH }} && dotnet ef database update